# PUT http://localhost:3001/api/blogs/5e964cc07b1e0127b02cbb76
# Content-Type: application/json

# {
#     "title": "willy's whatsup",
#     "author": "cuhauw",
#     "url": "cuhauw.com",
#     "likes": 100
# }

GET http://localhost:3001/api/blogs